root: true
parser: '@typescript-eslint/parser'
env:
  node: true
  browser: true
  es6: true
plugins:
  - '@typescript-eslint'
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
overrides:
  - files: ['*.ts', '*.tsx']
    rules:
      '@typescript-eslint/explicit-function-return-type':
        ['error']
rules:
  'no-unused-vars': 'off'
  'require-yield': 'off'
  'consistent-this':
    - 2
    - 'self'
  '@typescript-eslint/no-this-alias':
    - 'error'
    - allowDestructuring: true
      allowedNames: ['self']
  '@typescript-eslint/member-delimiter-style':
    - 'off'
    - delimiter: none
  '@typescript-eslint/explicit-function-return-type': 'off'
  '@typescript-eslint/no-use-before-define': 'off'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
  '@typescript-eslint/no-extra-semi': 'off'
  '@typescript-eslint/no-explicit-any': 'off'
